name: "Check and Format LaTeX Document"

on:
  push:
    branches:
      - 'docs-**'
    paths:
      - "docs/**/*.tex"
  pull_request:
    branches:
      - 'docs-**'
    types:
      - opened
      - synchronize
    paths:
      - "docs/**/*.tex"

jobs:
  format-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get changed .tex files
        id: changed-tex-files
        uses: tj-actions/changed-files@v47
        with:
          files: |
            **/*.tex
          diff_relative: true
          
      - name: Prepare root_file list
        if: steps.changed-tex-files.outputs.any_changed == 'true'
        run: |
          echo "ROOT_FILES<<EOF" >> $GITHUB_ENV
          echo "${{ steps.changed-tex-files.outputs.all_changed_files }}" | tr ' ' '\n' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV


      - name: Build changed TeX files
        if: steps.changed-tex-files.outputs.any_changed == 'true'
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ env.ROOT_FILES }}

      # - name: Install TeX Live and latexmk
        # run: |
          # sudo apt-get update
          # sudo apt-get install -y texlive-latex-extra texlive-fonts-extra texlive-science latexmk cargo
          # cargo install tex-fmt

      # - name: Get changed .tex files
        # id: changed-tex-files
        # uses: tj-actions/changed-files@v47
        # with:
          # files: |
            # **/*.tex
          # diff_relative: true

      # Format and Build LaTeX files
      # - name: Format and Build changed tex files
        # if: steps.changed-tex-files.outputs.any_changed == 'true'
        # env:
          # ALL_CHANGED_FILES: ${{ steps.changed-tex-files.outputs.all_changed_files }}
        # run: |
          # for file in ${ALL_CHANGED_FILES}; do
            # tex-fmt "$file"
            # folder=$(dirname "$file")
            # filename=$(basename -- "$file")
            # echo "Building $filename"
            # make -C "$folder"
          # done
          # git status
          
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: built-pdfs
          path: docs/**/*.pdf
          retention-days: 90
          overwrite: true

      - name: Commit & Push changes
        if: steps.changed-tex-files.outputs.any_changed == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            docs/**/*.tex
          author_name: "Github Action"
          author_email: "action@github.com"
          message: "Formatted LaTeX files"
     